#! /bin/bash

cd "$(dirname -- "${BASH_SOURCE[0]}")"
cd LeetCode

PROBLEM=$1

if [[ -z $PROBLEM ]]; then
  echo "problem not specified, eg. \"1. Two Sum\""
  exit 1
fi

NUMBER=$(echo "$PROBLEM" | sed -E 's/([0-9]+).*/\1/g')

echo problem NO.$NUMBER -- "$PROBLEM"

 cp -a "0. Template" "$PROBLEM"

cd "$PROBLEM"

rm Solution.cc # don't add cpp solution be default

if [[ x${NUMBER} != x ]]; then
  if [[ $(uname -s) == Darwin ]]; then
    sed -i '' "s/package problem0/package problem${NUMBER}/g" Solution.kt
  else
    sed -i "s/package problem0/package problem${NUMBER}/g" Solution.kt
  fi
fi
