#! /bin/bash

cd "$(dirname -- "${BASH_SOURCE[0]}")"
cd LeetCode

PROBLEM=$1

NUMBER=$(echo "$PROBLEM" | sed -E 's/([0-9]+).*/\1/g')

echo problem NO.$NUMBER -- "$PROBLEM"

 cp -a "0. Template" "$PROBLEM"

cd "$PROBLEM"
if [[ x${NUMBER} != x ]]; then
  if [[ $(uname -s) == Darwin ]]; then
    sed -i '' "s/package problem0/package problem${NUMBER}/g" Solution.kt
  else
    sed -i "s/package problem0/package problem${NUMBER}/g" Solution.kt
  fi
fi
